import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'tl' | 'en'; // tl = Tagalog/Taglish, en = English

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const LANGUAGE_KEY = '@app_language';

// Translations - Tagalog/Taglish as primary, English as secondary
const translations: Record<Language, Record<string, string>> = {
  tl: {
    // Login Screen
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Mag-sign In',
    'login.createAccount': 'Gumawa ng Account',
    'login.biometric': 'Mag-login gamit ang Biometric',
    'login.or': 'O',
    'login.continueGoogle': 'Magpatuloy gamit ang Google',
    'login.continueFacebook': 'Magpatuloy gamit ang Facebook',
    'login.continueGuest': 'Magpatuloy bilang Guest',
    'login.error': 'Error',
    'login.fillAllFields': 'Pakipunan ang lahat ng fields',
    'login.invalidEmail': 'Pakienter ang valid na email address',
    'login.failed': 'Hindi Makapag-login',
    'login.noCredentials': 'Walang nakatagong credentials. Mag-login muna ng normal.',
    'login.invalidCredentials': 'Hindi valid ang nakatagong credentials. Mag-login ng normal.',
    'login.biometricFailed': 'Hindi nagtagumpay ang biometric authentication.',
    'login.biometricUnavailable': 'Hindi available ang biometric authentication.',
    'login.googleFailed': 'Hindi Makapag-login sa Google',
    'login.facebookFailed': 'Hindi Makapag-login sa Facebook',
    'login.guestError': 'Hindi makapagpatuloy bilang guest. Pakisubukan ulit.',
    
    // Guest Agreement Modal
    'guest.title': 'Kasunduan para sa Guest Access',
    'guest.message': 'Bilang guest, ang iyong mga report ay pansamantala lamang at mawawala kapag nag-logout ka. Pakisang-ayunan ang aming mga patakaran para makapagpatuloy.',
    'guest.agreementRequired': 'Kailangan ng Kasunduan',
    'guest.agreementMessage': 'Pakisang-ayunan ang Terms of Service at Privacy Policy para makapagpatuloy bilang guest.',
    'guest.agreeTerms': 'Sumasang-ayon ako sa',
    'guest.termsOfService': 'Terms of Service',
    'guest.and': 'at',
    'guest.privacyPolicy': 'Privacy Policy',
    'guest.cancel': 'Kanselahin',
    'guest.continue': 'Magpatuloy',
    
    // Onboarding
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.getStarted': 'Magpatuloy',
    'onboarding.slide1.title': 'Mag-report ng Insidente',
    'onboarding.slide1.description': 'Direktang i-report ang mga krimen, sunog, at sakuna. Gamit ang GPS, matutukoy agad ng mga awtoridad ang iyong exact at tunay na location',
    'onboarding.slide2.title': 'Kumuha ng Ebidensya',
    'onboarding.slide2.description': 'Kumuha ng litrato o video bilang ebidensya. Ang iyong media ay ligtas na ina-upload at naka-attach sa iyong report.',
    'onboarding.slide3.title': 'I-track ang Status',
    'onboarding.slide3.description': 'Makakuha ng updates sa iyong mga report. Malaman kung kailan may naka-assign na opisyal at tumutugon sa iyong insidente.',
    'onboarding.slide4.title': 'Manatiling Ligtas',
    'onboarding.slide4.description': 'Tumulong na panatilihing ligtas ang Camarines Norte. Ang iyong mga report ay tumutulong sa mga awtoridad na mas mabilis na tumugon sa mga emergency.',
    
    // Language
    'language.select': 'Pumili ng Wika',
    'language.tagalog': 'Tagalog',
    'language.english': 'English',
    'language.title': 'Wika ng App',
    'language.description': 'Piliin ang wika ng app',

    // Common
    'common.back': '← Bumalik',
    'common.save': 'I-save',
    'common.cancel': 'Kanselahin',
    'common.submit': 'Isumite',
    'common.continue': 'Magpatuloy',
    'common.error': 'Error',
    'common.success': 'Tagumpay',
    'common.loading': 'Naglo-load...',
    'common.required': 'Kinakailangan',
    'common.logout': 'Mag-logout',
    'common.confirm': 'Kumpirma',

    // Welcome Screen
    'welcome.title': 'Mabuhay!',
    'welcome.subtitle': 'Mag-report ng insidente sa Camarines Norte',
    'welcome.signIn': 'Mag-sign In',
    'welcome.createAccount': 'Gumawa ng Account',
    'welcome.continueGuest': 'Magpatuloy bilang Guest',

    // Sign Up Screen
    'signup.title': 'Gumawa ng Account',
    'signup.fullName': 'Buong Pangalan',
    'signup.dateOfBirth': 'Petsa ng Kapanganakan',
    'signup.email': 'Email Address',
    'signup.phone': 'Phone Number',
    'signup.phonePlaceholder': '09XX XXX XXXX',
    'signup.password': 'Password',
    'signup.confirmPassword': 'Kumpirmahin ang Password',
    'signup.agreeTerms': 'Sumasang-ayon ako sa',
    'signup.alreadyHaveAccount': 'May account na? Mag-sign in',
    'signup.error.fillAllFields': 'Pakipunan ang lahat ng fields',
    'signup.error.agreeTerms': 'Pakisang-ayunan ang Terms of Service at Privacy Policy para makapagpatuloy.',
    'signup.error.minAge': '13 taong gulang para makapag-register',
    'signup.error.invalidAge': 'Pakienter ang valid na petsa ng kapanganakan',
    'signup.error.nameTooShort': 'Ang pangalan ay dapat may 2 characters ',
    'signup.error.invalidEmail': 'Pakienter ang valid na email address',
    'signup.error.invalidPhone': 'Pakienter ang valid na Philippine mobile number (09XX-XXX-XXXX)',
    'signup.error.passwordTooShort': 'Ang password ay dapat may 6 characters ',
    'signup.error.passwordMismatch': 'Hindi pareho ang mga password',
    'signup.verificationRequired': 'Kailangan ng Verification',
    'signup.verificationMessage': 'Isang 6-digit code ang ipinadala sa iyong email. Pakiverify ang iyong account para makapagpatuloy.',

    // Home Screen
    'home.greeting': 'Hello',
    'home.guestUser': 'Guest User',
    'home.reportIncident': 'Mag-report ng Insidente',
    'home.selectAgency': 'Pumili ng agency para mag-report:',
    'home.crimeReport': 'Krimen',
    'home.crimeDesc': 'I-report sa PNP',
    'home.fireReport': 'Sunog',
    'home.fireDesc': 'I-report sa BFP',
    'home.disasterReport': 'Sakuna',
    'home.disasterDesc': 'I-report sa PDRRMO',
    'home.recentReports': 'Mga Kamakailang Report',
    'home.viewAll': 'Tingnan Lahat',
    'home.noReports': 'Wala pang mga report',
    'home.stats': 'Mga Estadistika',
    'home.totalReports': 'Kabuuang Reports',
    'home.pending': 'Pending',
    'home.resolved': 'Nalutas',

    // Reports Screen
    'reports.title': 'Aking mga Report',
    'reports.noReports': 'Wala ka pang mga report',
    'reports.noReportsDesc': 'Ang iyong mga naisumiteng report ay lalabas dito',
    'reports.status.pending': 'Pending',
    'reports.status.acknowledged': 'Natanggap',
    'reports.status.dispatched': 'Naipadala',
    'reports.status.responding': 'Tumutugon',
    'reports.status.resolved': 'Resoloved',
    'reports.status.closed': 'Closed',
    'reports.filter.all': 'All',
    'reports.filter.pending': 'Pending',
    'reports.filter.active': 'Active',
    'reports.filter.resolved': 'Closed',
    'reports.deleteQueuedTitle': 'Tanggalin ang Queued Report?',
    'reports.deleteQueuedMessage': 'Ang report na ito ay hindi pa naisusumite. Sigurado ka bang gusto mong tanggalin ito?',

    // Profile Screen
    'profile.title': 'Profile',
    'profile.guestAccount': '⚠️ Guest Account',
    'profile.guestWarning': 'Gumagamit ka ng pansamantalang guest account. Mawawala ang iyong mga report kapag nag-logout o nagsara ng app. Gumawa ng account para ma-save ang iyong mga report at makatanggap ng updates.',
    'profile.createAccount': 'Gumawa ng Account',
    'profile.personalDetails': 'Personal na Detalye',
    'profile.displayName': 'Display Name',
    'profile.enterName': 'Ilagay ang iyong pangalan',
    'profile.email': 'Email',
    'profile.emailCannotChange': 'Hindi mababago ang email',
    'profile.phoneNumber': 'Phone Number',
    'profile.dateOfBirth': 'Petsa ng Kapanganakan',
    'profile.selectDOB': 'Pumili ng Petsa ng Kapanganakan',
    'profile.savePersonalDetails': 'I-save ang Personal na Detalye',
    'profile.preferences': 'Mga Kagustuhan',
    'profile.biometricLogin': 'Biometric Login',
    'profile.biometricDesc': 'I-save ang credentials para sa biometric login. Mag-login ng normal muna pagkatapos i-enable.',
    'profile.notifications': 'Mga Notification',
    'profile.notificationsDesc': 'Makatanggap ng updates tungkol sa iyong mga report',
    'profile.showStats': 'Ipakita ang Estadistika',
    'profile.showStatsDesc': 'Ipakita ang public stats sa home screen',
    'profile.savePreferences': 'I-save ang mga Kagustuhan',
    'profile.signOut': 'Mag-sign Out',
    'profile.signOutConfirm': 'Sigurado ka bang gusto mong mag-logout?',
    'profile.signOutGuestTitle': '⚠️ Logout bilang Guest',
    'profile.signOutGuestMessage': 'Mawawala ang iyong mga report kung mag-logout ka. Hindi na mababawi ang guest accounts. Sigurado ka ba?',
    'profile.appInfo': 'iReport Camarines Norte',
    'profile.version': 'Version',
    'profile.success': 'Tagumpay',
    'profile.personalDetailsSaved': 'Na-update na ang personal na detalye',
    'profile.preferencesSaved': 'Na-update na ang mga kagustuhan',
    'profile.error': 'Error',
    'profile.saveFailed': 'Hindi na-save',
    'profile.invalidDate': 'Hindi Valid na Petsa',
    'profile.invalidDateMessage': 'Pakienter ang valid na petsa ng kapanganakan',
    'profile.ageRestriction': 'Limitasyon sa Edad',
    'profile.ageRestrictionMessage': 'Dapat ay 13 taong gulang ka man lang para gamitin ang app na ito',
    'profile.selectYear': '📅 Pumili ng Taon',
    'profile.selectMonth': '📆 Pumili ng Buwan',
    'profile.selectDay': '📍 Pumili ng Araw',
    'profile.exitGuest': 'Lumabas sa Guest Mode',
    'profile.exitGuestMessage': 'Sigurado ka bang gusto mong lumabas sa guest mode?',

    // Incident Form
    'form.crimeReport': 'Report ng Krimen',
    'form.fireReport': 'Report ng Sunog',
    'form.disasterReport': 'Report ng Sakuna',
    'form.incidentReport': 'Report ng Insidente',
    'form.incidentDetails': 'Mga Detalye ng Insidente',
    'form.reportInfo': '📋 Impormasyon ng Report',
    'form.yourInfo': '👤 Iyong Impormasyon',
    'form.fullName': 'Buong Pangalan *',
    'form.enterFullName': 'Ilagay ang iyong buong pangalan',
    'form.age': 'Edad *',
    'form.enterAge': 'Ilagay ang iyong edad',
    'form.contactNumber': 'Contact Number *',
    'form.contactHelper': 'Kinakailangan para makontak ka ng mga responder tungkol sa insidenteng ito',
    'form.yourLocation': '📍 Iyong Kasalukuyang Lokasyon',
    'form.incidentLocation': '🚨 Lokasyon ng Insidente',
    'form.description': 'Paglalarawan ng Insidente *',
    'form.descriptionPlaceholder': 'Ilarawan kung ano ang nangyari, kailan nangyari, at iba pang mahahalagang detalye...',
    'form.quickSelect': 'Mabilis na Pagpili:',
    'form.orTypeBelow': 'O mag-type sa ibaba:',
    'form.submitReport': 'Isumite ang Report',
    'form.submitting': 'Isubmite...',
    'form.evidence': 'Ebidensya',
    'form.photos': 'litrato/video',
    'form.error.nameRequired': 'Pakienter ang iyong pangalan.',
    'form.error.nameTooShort': 'Ang pangalan ay dapat may 2 characters man lang.',
    'form.error.nameTooLong': 'Ang pangalan ay dapat mas maikli sa 100 characters.',
    'form.error.ageRequired': 'Pakienter ang valid na edad.',
    'form.error.ageInvalid': 'Ang edad ay dapat nasa pagitan ng 13 at 120.',
    'form.error.phoneRequired': 'Pakienter ang iyong contact number para makontak ka ng mga responder.',
    'form.error.phoneInvalid': 'Pakienter ang valid na Philippine mobile number (hal., 09171234567).',
    'form.error.descriptionRequired': 'Pakimagbigay ng paglalarawan ng insidente.',
    'form.error.descriptionTooShort': 'Pakimagbigay ng hindi bababa sa 10 characters na naglalarawan ng insidente.',
    'form.error.descriptionTooLong': 'Ang paglalarawan ay dapat mas maikli sa 5000 characters.',
    'form.crime.theft': 'Nakawan/Robbery na naganap',
    //'form.crime.suspicious': 'Kahina-hinalang tao/aktibidad',
    'form.crime.assault': 'Pisikal na pag-atake/away',
    'form.crime.vandalism': 'Vandalism/pinsala sa property',
    'form.crime.drugs': 'Aktibidad na may kinalaman sa droga',
    'form.crime.domestic': 'Gulo sa tahanan',
    'form.fire.building': 'Sunog sa gusali/bahay',
    'form.fire.vehicle': 'Sunog sa sasakyan',
    'form.fire.electrical': 'Sunog mula sa kuryente',
    'form.fire.grass': 'Sunog sa damuhan/kagubatan',
    'form.fire.smoke': 'Usok/amoy ng nasusunog',
    'form.fire.gas': 'Gas leak',
    'form.disaster.flood': 'Pagbaha sa lugar',
    'form.disaster.landslide': 'Landslide/mudslide',
    'form.disaster.tree': 'Nabuwal na puno na humaharang sa daan',
    'form.disaster.storm': 'Pinsala sa istruktura mula sa bagyo',
    'form.disaster.powerlines': 'Nahulog na linya ng kuryente',
    'form.disaster.earthquake': 'Pinsala mula sa lindol',
    'form.continueToReport': 'Magpatuloy sa Report Form',
    'form.reviewReport': 'Suriin ang Report',
    'form.validationError': 'Error sa Validation',
    'form.yearsOld': 'taong gulang',

    // Camera Screen
    'camera.title': 'Kumuha ng Ebidensya',
    'camera.subtitle': 'Kumuha ng litrato o video ng insidente',
    'camera.takePhoto': '📷 Kumuha ng Litrato',
    'camera.takeVideo': '🎥 Kumuha ng Video',
    'camera.chooseFromGallery': '🖼️ Pumili mula sa Gallery',
    'camera.takeAnotherPhoto': '📷 Kumuha ng Isa Pang Litrato',
    'camera.continueToForm': '📝 Magpatuloy sa Report Form',
    'camera.capturedMedia': 'Nakuhang Ebidensya',
    'camera.tapToPreview': 'I-tap para i-preview',
    'camera.permissionRequired': 'Kailangan ng Pahintulot',
    'camera.cameraPermission': 'Kailangan naming i-access ang iyong camera para kumuha ng litrato.',
    'camera.locationPermission': 'Kailangan naming i-access ang iyong lokasyon para sa report.',
    'camera.grantPermission': 'Magbigay ng Pahintulot',
    'camera.yourLocation': '📍 Iyong Lokasyon',
    'camera.locationLoading': 'Kinukuha ang lokasyon...',
    'camera.locationUnavailable': 'Hindi available ang lokasyon',
    'camera.edit': 'I-edit',
    'camera.delete': 'Tanggalin',
    'camera.photo': 'litrato',
    'camera.video': 'video',
    'camera.photos': 'mga litrato',
    'camera.videos': 'mga video',
    'camera.mediaRequired': 'Kailangan ng Ebidensya',
    'camera.mediaRequiredMessage': 'Pakikuha ng kahit isang litrato o video bilang ebidensya bago magpatuloy.',
    'camera.locationRequired': 'Kailangan ng Lokasyon',
    'camera.locationRequiredMessage': 'Pakihintay na makuha ang iyong lokasyon bago magpatuloy.',
    'camera.saveDraftTitle': 'I-save bilang Draft?',
    'camera.saveDraftMessage': 'Gusto mo bang i-save ang report na ito bilang draft? Maaari mo itong ipagpatuloy mamaya mula sa Aking mga Report.',
    'camera.saveDraft': 'I-save ang Draft',
    'camera.discard': 'Itapon',

    // Incident Details
    'details.incidentLocation': '🚨 Lokasyon ng Insidente',
    'details.reporterLocation': '📍 Lokasyon ng Nag-ulat',

    // Confirm Report
    'confirm.title': 'Kumpirmahin ang Report',
    'confirm.subtitle': 'Suriin bago isumite',
    'confirm.reviewDetails': 'Suriin ang mga detalye ng iyong report bago isumite',
    'confirm.summary': '✅ Buod ng Report',
    'confirm.reportType': 'Uri',
    'confirm.crimeReport': 'Report ng Krimen',
    'confirm.fireReport': 'Report ng Sunog',
    'confirm.disasterReport': 'Report ng Sakuna',
    'confirm.incidentReport': 'Report ng Insidente',
    'confirm.reporter': 'Nag-uulat',
    'confirm.location': 'Lokasyon',
    'confirm.dateTime': 'Petsa at Oras',
    'confirm.description': 'Paglalarawan',
    'confirm.evidence': 'Ebidensya',
    'confirm.items': 'mga item',
    'confirm.noEvidence': 'Walang naka-attach na media',
    'confirm.edit': '✏️ I-edit ang Report',
    'confirm.submit': '📤 Isumite ang Report',
    'confirm.submitting': 'Isinusumite...',
    'confirm.agreement': 'Sa pagsusumite ng report na ito, kinukumpirma ko na ang impormasyong ibinigay ay tama ayon sa aking kaalaman at nauunawaan ko na ang pagsusumite ng maling report ay maaaring magresulta sa legal na kahihinatnan sa ilalim ng Revised Penal Code (Artikulo 171 at 172) at ng Cybercrime Prevention Act of 2012.',
    'confirm.noInternet': 'Walang Koneksyon sa Internet',
    'confirm.offlineMessage': 'Ang iyong report ay ise-save at awtomatikong isusubmit kapag online ka na ulit.',
    'confirm.tooManyFiles': 'Masyadong Maraming File',
    'confirm.maxFiles': 'Maaari ka lang mag-upload ng hanggang 10 litrato/video bawat report.',
    'confirm.submissionFailed': 'Hindi Naisumite',
    'confirm.tryAgain': 'Hindi naisumite ang report. Pakisubukan ulit.',
    'confirm.tooManyReports': 'Masyadong Maraming Report',
    'confirm.rateLimitMessage': 'Maaari ka lang magsumite ng 5 report bawat oras. Pakisubukan ulit mamaya.',
    'confirm.invalidData': 'Hindi Valid na Data',
    'confirm.contentTooLong': 'Masyadong Mahaba ang Nilalaman',
    'confirm.duplicateTitle': 'Posibleng Duplicate na Report',
    'confirm.duplicateMessage': 'May katulad na report na naisumite mula sa parehong lokasyon kamakailan. Sigurado ka bang gusto mong isumite ito?',
    'confirm.submitAnyway': 'Isumite Pa Rin',

    // Report Success
    'success.title': 'Naisubmit na ang Report!',
    'success.titleOffline': 'Naka-queue na ang Report!',
    'success.message': 'Ang iyong report ay matagumpay na naisubmit.',
    'success.messageOffline': 'Ang iyong report ay naka-save at awtomatikong isusubmit kapag online ka na ulit.',
    'success.trackingId': 'Tracking Code',
    'success.trackingHint': 'I-save ang code na ito para ma-track ang status ng iyong report',
    'success.offlineTitle': 'Naka-save Offline',
    'success.offlineMessage': 'Ang iyong report ay ligtas na naka-save sa iyong device at awtomatikong isusubmit kapag may internet connection na ulit.',
    'success.whatNext': 'Ano ang susunod?',
    'success.step1': 'Sinusuri ng desk officer ang iyong report',
    'success.step2': 'May field officer na i-aassign para tumugon',
    'success.step3': 'Makakatanggap ka ng updates sa status ng iyong report',
    'success.goHome': 'Bumalik sa Home',
    'success.viewReports': 'Tingnan ang Aking mga Report',
    'success.emergencyNote': '🚨 Sa kaso ng emergency, direktang tumawag sa hotline',
    'success.assignedTo': 'Naka-assign sa',
    'success.assignedHint': 'Ang pinakamalapit na istasyon ay awtomatikong na-notify',

    // Tabs
    'tabs.home': 'Home',
    'tabs.reports': 'Aking mga Report',
    'tabs.profile': 'Profile',
  },
  en: {
    // Login Screen
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.createAccount': 'Create Account',
    'login.biometric': 'Login with Biometric',
    'login.or': 'OR ',
    'login.continueGoogle': 'Continue with Google',
    'login.continueFacebook': 'Continue with Facebook',
    'login.continueGuest': 'Continue as Guest',
    'login.error': 'Error',
    'login.fillAllFields': 'Please fill in all fields',
    'login.invalidEmail': 'Please enter a valid email address',
    'login.failed': 'Login Failed',
    'login.noCredentials': 'No saved credentials found. Please login normally first.',
    'login.invalidCredentials': 'Saved credentials are invalid. Please login normally.',
    'login.biometricFailed': 'Biometric authentication was not successful.',
    'login.biometricUnavailable': 'Biometric authentication is not available.',
    'login.googleFailed': 'Google Login Failed',
    'login.facebookFailed': 'Facebook Login Failed',
    'login.guestError': 'Failed to continue as guest. Please try again.',
    
    // Guest Agreement Modal
    'guest.title': 'Guest Access Agreement',
    'guest.message': 'As a guest, your reports will be temporary and lost if you logout. Please agree to our policies to continue.',
    'guest.agreementRequired': 'Agreement Required',
    'guest.agreementMessage': 'Please agree to the Terms of Service and Privacy Policy to continue as guest.',
    'guest.agreeTerms': 'I agree to the',
    'guest.termsOfService': 'Terms of Service',
    'guest.and': 'and',
    'guest.privacyPolicy': 'Privacy Policy',
    'guest.cancel': 'Cancel',
    'guest.continue': 'Continue',
    
    // Onboarding
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.getStarted': 'Get Started',
    'onboarding.slide1.title': 'Report Incidents',
    'onboarding.slide1.description': 'Quickly report crimes, fires, and disasters to the right authorities with accurate GPS location tagging.',
    'onboarding.slide2.title': 'Capture Evidence',
    'onboarding.slide2.description': 'Take photos or videos as evidence. Your media is securely uploaded and attached to your report.',
    'onboarding.slide3.title': 'Track Status',
    'onboarding.slide3.description': 'Get updates on your reports. Know when officers are assigned and responding to your incident.',
    'onboarding.slide4.title': 'Stay Safe',
    'onboarding.slide4.description': 'Help keep Camarines Norte safe. Your reports help authorities respond faster to emergencies.',
    
    // Language
    'language.select': 'Select Language',
    'language.tagalog': 'Tagalog',
    'language.english': 'English',
    'language.title': 'App Language',
    'language.description': 'Choose the app language',

    // Common
    'common.back': '← Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.continue': 'Continue',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.loading': 'Loading...',
    'common.required': 'Required',
    'common.logout': 'Logout',
    'common.confirm': 'Confirm',

    // Welcome Screen
    'welcome.title': 'Welcome!',
    'welcome.subtitle': 'Report incidents in Camarines Norte',
    'welcome.signIn': 'Sign In',
    'welcome.createAccount': 'Create Account',
    'welcome.continueGuest': 'Continue as Guest',

    // Sign Up Screen
    'signup.title': 'Create Account',
    'signup.fullName': 'Full Name',
    'signup.dateOfBirth': 'Date of Birth',
    'signup.email': 'Email Address',
    'signup.phone': 'Phone Number',
    'signup.phonePlaceholder': '09XX XXX XXXX',
    'signup.password': 'Password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.agreeTerms': 'I agree to the',
    'signup.alreadyHaveAccount': 'Already have an account? Sign in',
    'signup.error.fillAllFields': 'Please fill in all fields',
    'signup.error.agreeTerms': 'Please agree to the Terms of Service and Privacy Policy to continue.',
    'signup.error.minAge': 'You must be at least 13 years old to register',
    'signup.error.invalidAge': 'Please enter a valid date of birth',
    'signup.error.nameTooShort': 'Name must be at least 2 characters',
    'signup.error.invalidEmail': 'Please enter a valid email address',
    'signup.error.invalidPhone': 'Please enter a valid Philippine mobile number (09XX-XXX-XXXX)',
    'signup.error.passwordTooShort': 'Password must be at least 6 characters',
    'signup.error.passwordMismatch': 'Passwords do not match',
    'signup.verificationRequired': 'Verification Required',
    'signup.verificationMessage': 'A 6-digit code has been sent to your email. Please verify your account to continue.',

    // Home Screen
    'home.greeting': 'Hello',
    'home.guestUser': 'Guest User',
    'home.reportIncident': 'Report an Incident',
    'home.selectAgency': 'Select an agency to report to:',
    'home.crimeReport': 'Crime',
    'home.crimeDesc': 'Report to PNP',
    'home.fireReport': 'Fire',
    'home.fireDesc': 'Report to BFP',
    'home.disasterReport': 'Disaster',
    'home.disasterDesc': 'Report to PDRRMO',
    'home.recentReports': 'Recent Reports',
    'home.viewAll': 'View All',
    'home.noReports': 'No reports yet',
    'home.stats': 'Statistics',
    'home.totalReports': 'Total Reports',
    'home.pending': 'Pending',
    'home.resolved': 'Resolved',

    // Reports Screen
    'reports.title': 'My Reports',
    'reports.noReports': 'No reports yet',
    'reports.noReportsDesc': 'Your submitted reports will appear here',
    'reports.status.pending': 'Pending',
    'reports.status.acknowledged': 'Acknowledged',
    'reports.status.dispatched': 'Dispatched',
    'reports.status.responding': 'Responding',
    'reports.status.resolved': 'Resolved',
    'reports.status.closed': 'Closed',
    'reports.filter.all': 'All',
    'reports.filter.pending': 'Pending',
    'reports.filter.active': 'Active',
    'reports.filter.resolved': 'Resolved',
    'reports.deleteQueuedTitle': 'Delete Queued Report?',
    'reports.deleteQueuedMessage': 'This report has not been submitted yet. Are you sure you want to delete it?',

    // Profile Screen
    'profile.title': 'Profile',
    'profile.guestAccount': '⚠️ Guest Account',
    'profile.guestWarning': 'You\'re using a temporary guest account. Your reports will be lost if you logout or close the app. Create an account to save your reports permanently and receive updates.',
    'profile.createAccount': 'Create Account',
    'profile.personalDetails': 'Personal Details',
    'profile.displayName': 'Display Name',
    'profile.enterName': 'Enter your name',
    'profile.email': 'Email',
    'profile.emailCannotChange': 'Email cannot be changed',
    'profile.phoneNumber': 'Phone Number',
    'profile.dateOfBirth': 'Date of Birth',
    'profile.selectDOB': 'Select Date of Birth',
    'profile.savePersonalDetails': 'Save Personal Details',
    'profile.preferences': 'Preferences',
    'profile.biometricLogin': 'Biometric Login',
    'profile.biometricDesc': 'Save credentials for biometric login. Login normally once after enabling.',
    'profile.notifications': 'Notifications',
    'profile.notificationsDesc': 'Receive updates about your reports',
    'profile.showStats': 'Show Statistics',
    'profile.showStatsDesc': 'Display public stats on home screen',
    'profile.savePreferences': 'Save Preferences',
    'profile.signOut': 'Sign Out',
    'profile.signOutConfirm': 'Are you sure you want to logout?',
    'profile.signOutGuestTitle': '⚠️ Logout as Guest',
    'profile.signOutGuestMessage': 'Your reports will be permanently lost if you logout. Guest accounts cannot be recovered. Are you sure?',
    'profile.appInfo': 'iReport Camarines Norte',
    'profile.version': 'Version',
    'profile.success': 'Success',
    'profile.personalDetailsSaved': 'Personal details updated successfully',
    'profile.preferencesSaved': 'Preferences updated successfully',
    'profile.error': 'Error',
    'profile.saveFailed': 'Failed to save',
    'profile.invalidDate': 'Invalid Date',
    'profile.invalidDateMessage': 'Please enter a valid date of birth',
    'profile.ageRestriction': 'Age Restriction',
    'profile.ageRestrictionMessage': 'You must be at least 13 years old to use this app',
    'profile.selectYear': '📅 Select Year',
    'profile.selectMonth': '📆 Select Month',
    'profile.selectDay': '📍 Select Day',
    'profile.exitGuest': 'Exit Guest Mode',
    'profile.exitGuestMessage': 'Are you sure you want to exit guest mode?',

    // Incident Form
    'form.crimeReport': 'Crime Report',
    'form.fireReport': 'Fire Report',
    'form.disasterReport': 'Disaster Report',
    'form.incidentReport': 'Incident Report',
    'form.incidentDetails': 'Incident Details',
    'form.reportInfo': '📋 Report Information',
    'form.yourInfo': '👤 Your Information',
    'form.fullName': 'Full Name *',
    'form.enterFullName': 'Enter your full name',
    'form.age': 'Age *',
    'form.enterAge': 'Enter your age',
    'form.contactNumber': 'Contact Number *',
    'form.contactHelper': 'Required so responders can contact you about this incident',
    'form.yourLocation': '📍 Your Current Location',
    'form.incidentLocation': '🚨 Incident Location',
    'form.description': 'Incident Description *',
    'form.descriptionPlaceholder': 'Describe what happened, when it happened, and any other relevant details...',
    'form.quickSelect': 'Quick Select:',
    'form.orTypeBelow': 'Or type your own below:',
    'form.submitReport': 'Submit Report',
    'form.submitting': 'Submitting...',
    'form.evidence': 'Evidence',
    'form.photos': 'photo(s)/video(s)',
    'form.error.nameRequired': 'Please enter your name.',
    'form.error.nameTooShort': 'Name must be at least 2 characters.',
    'form.error.nameTooLong': 'Name must be less than 100 characters.',
    'form.error.ageRequired': 'Please enter a valid age.',
    'form.error.ageInvalid': 'Age must be between 13 and 120.',
    'form.error.phoneRequired': 'Please enter your contact number so responders can reach you.',
    'form.error.phoneInvalid': 'Please enter a valid Philippine mobile number (e.g., 09171234567).',
    'form.error.descriptionRequired': 'Please provide a description of the incident.',
    'form.error.descriptionTooShort': 'Please provide at least 10 characters describing the incident.',
    'form.error.descriptionTooLong': 'Description must be less than 5000 characters.',
    'form.crime.theft': 'Theft/Robbery',
    //'form.crime.suspicious': 'Suspicious person/activity',
    'form.crime.assault': 'Physical assault/fight',
    'form.crime.vandalism': 'Vandalism/property damage',
    'form.crime.drugs': 'Drug-related activity',
    'form.crime.domestic': 'Domestic disturbance',
    'form.fire.building': 'Building/house fire',
    'form.fire.vehicle': 'Vehicle fire',
    'form.fire.electrical': 'Electrical fire',
    'form.fire.grass': 'Grass/forest fire',
    'form.fire.smoke': 'Smoke/burning smell',
    'form.fire.gas': 'Gas leak',
    'form.disaster.flood': 'Flooding in area',
    'form.disaster.landslide': 'Landslide/mudslide',
    'form.disaster.tree': 'Fallen tree blocking road',
    'form.disaster.storm': 'Structural damage from storm',
    'form.disaster.powerlines': 'Power lines down',
    'form.disaster.earthquake': 'Earthquake damage',
    'form.continueToReport': 'Continue to Report Form',
    'form.reviewReport': 'Review Report',
    'form.validationError': 'Validation Error',
    'form.yearsOld': 'years old',

    // Camera Screen
    'camera.title': 'Capture Evidence',
    'camera.subtitle': 'Take photos or videos of the incident',
    'camera.takePhoto': '📷 Take Photo',
    'camera.takeVideo': '🎥 Take Video',
    'camera.chooseFromGallery': '🖼️ Choose from Gallery',
    'camera.takeAnotherPhoto': '📷 Take Another Photo',
    'camera.continueToForm': '📝 Continue to Report Form',
    'camera.capturedMedia': 'Captured Evidence',
    'camera.tapToPreview': 'Tap to preview',
    'camera.permissionRequired': 'Permission Required',
    'camera.cameraPermission': 'We need access to your camera to take photos.',
    'camera.locationPermission': 'We need access to your location for the report.',
    'camera.grantPermission': 'Grant Permission',
    'camera.yourLocation': '📍 Your Location',
    'camera.locationLoading': 'Getting location...',
    'camera.locationUnavailable': 'Location unavailable',
    'camera.edit': 'Edit',
    'camera.delete': 'Delete',
    'camera.photo': 'photo',
    'camera.video': 'video',
    'camera.photos': 'photos',
    'camera.videos': 'videos',
    'camera.mediaRequired': 'Evidence Required',
    'camera.mediaRequiredMessage': 'Please take at least one photo or video as evidence before continuing.',
    'camera.locationRequired': 'Location Required',
    'camera.locationRequiredMessage': 'Please wait for your location to be detected before continuing.',
    'camera.saveDraftTitle': 'Save as Draft?',
    'camera.saveDraftMessage': 'Would you like to save this report as a draft? You can continue it later from My Reports.',
    'camera.saveDraft': 'Save Draft',
    'camera.discard': 'Discard',

    // Incident Details
    'details.incidentLocation': '🚨 Incident Location',
    'details.reporterLocation': '📍 Reporter Location',

    // Confirm Report
    'confirm.title': 'Confirm Report',
    'confirm.subtitle': 'Review before submitting',
    'confirm.reviewDetails': 'Review your report details before submitting',
    'confirm.summary': '✅ Report Summary',
    'confirm.reportType': 'Type',
    'confirm.crimeReport': 'Crime Report',
    'confirm.fireReport': 'Fire Report',
    'confirm.disasterReport': 'Disaster Report',
    'confirm.incidentReport': 'Incident Report',
    'confirm.reporter': 'Reporter',
    'confirm.location': 'Location',
    'confirm.dateTime': 'Date & Time',
    'confirm.description': 'Description',
    'confirm.evidence': 'Evidence',
    'confirm.items': 'items',
    'confirm.noEvidence': 'No media attached',
    'confirm.edit': '✏️ Edit Report',
    'confirm.submit': '📤 Submit Report',
    'confirm.submitting': 'Submitting...',
    'confirm.agreement': 'By submitting this report, I confirm that the information provided is accurate to the best of my knowledge and understand that filing a false report may result in legal consequences under the Revised Penal Code (Articles 171 and 172) and the Cybercrime Prevention Act of 2012.',
    'confirm.noInternet': 'No Internet Connection',
    'confirm.offlineMessage': 'Your report will be saved and submitted automatically when you\'re back online.',
    'confirm.tooManyFiles': 'Too Many Files',
    'confirm.maxFiles': 'You can only upload up to 10 photos/videos per report.',
    'confirm.submissionFailed': 'Submission Failed',
    'confirm.tryAgain': 'Failed to submit report. Please try again.',
    'confirm.tooManyReports': 'Too Many Reports',
    'confirm.rateLimitMessage': 'You can only submit 5 reports per hour. Please try again later.',
    'confirm.invalidData': 'Invalid Data',
    'confirm.contentTooLong': 'Content Too Long',
    'confirm.duplicateTitle': 'Possible Duplicate Report',
    'confirm.duplicateMessage': 'A similar report was recently submitted from the same location. Are you sure you want to submit this?',
    'confirm.submitAnyway': 'Submit Anyway',

    // Report Success
    'success.title': 'Report Submitted!',
    'success.titleOffline': 'Report Queued!',
    'success.message': 'Your report has been successfully submitted.',
    'success.messageOffline': 'Your report has been saved and will be automatically submitted when you\'re back online.',
    'success.trackingId': 'Tracking Code',
    'success.trackingHint': 'Save this code to track your report status',
    'success.offlineTitle': 'Saved Offline',
    'success.offlineMessage': 'Your report is safely stored on your device and will be submitted automatically when internet connection is restored.',
    'success.whatNext': 'What happens next?',
    'success.step1': 'Your report is being reviewed by the desk officer',
    'success.step2': 'A field officer will be assigned to respond',
    'success.step3': 'You\'ll receive updates on your report status',
    'success.goHome': 'Return to Home',
    'success.viewReports': 'View My Reports',
    'success.emergencyNote': '🚨 In case of immediate emergency, please call the hotline directly',
    'success.assignedTo': 'Assigned to',
    'success.assignedHint': 'The nearest station has been automatically notified',

    // Tabs
    'tabs.home': 'Home',
    'tabs.reports': 'My Reports',
    'tabs.profile': 'Profile',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('tl'); // Default to Tagalog
  const [isLoaded, setIsLoaded] = useState(false);

  // Load saved language preference on mount
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem(LANGUAGE_KEY);
        if (savedLanguage === 'en' || savedLanguage === 'tl') {
          setLanguageState(savedLanguage);
        }
        // If no saved preference, keep default (Tagalog)
      } catch (error) {
        console.error('Failed to load language preference:', error);
      } finally {
        setIsLoaded(true);
      }
    };
    loadLanguage();
  }, []);

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem(LANGUAGE_KEY, lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Failed to save language preference:', error);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Don't render children until language is loaded to prevent flash
  if (!isLoaded) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
